on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    container: node:16-bullseye
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup app dependencies
      env:
        PGDATABASE: "${{secrets.PGDATABASE}}"
        PGHOST: "${{secrets.PGHOST}}"
        PGPASSWORD: "${{secrets.PGPASSWORD}}"
        PGPORT: "${{secrets.PGPORT}}"
        PGUSER: "${{secrets.PGUSER}}"
      run: |
        apt-get update
        apt-get install --yes postgresql
        apt-get install --yes postgresql-client
        apt-get install --yes dnsutils
        nslookup parkour-history-pg-prod.chfcrg2vxvx9.us-east-2.rds.amazonaws.com
        psql -h "$PGHOST" -U "$PGUSER" -d "$PGDATABASE" -l
        cd ./jobs/snapshot
        npm install


    - name: Run Snapshot
      env:
        PG_CONNECTION_URL: "${{secrets.PG_CONNECTION_URL}}"
      run: |
        cd ./jobs/snapshot
        node index.js

    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        author_name: Parkour History Bot
        author_email: parkour.history.archiver@gmail.com
        message: 'Update Snapshot'
        add: './docs/_data/snapshot.json'
        push: true
