on:
  workflow_dispatch:
  schedule:
    - cron: "13 1,7,13,19 * * *" # https://crontab.guru/#13_1,7,13,19_*_*_*

jobs:
  snapshot:
    env:
      PG_CONNECTION_URL: "${{secrets.PG_CONNECTION_URL}}"

    runs-on: ubuntu-latest

    container: node:16-bullseye
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
    - name: Setup directory ownership
      run : git config --global --add safe.directory /__w/parkour-history-website/parkour-history-website

    - name: Setup app dependencies
      run: |
        cd ./jobs/snapshot
        npm install

    - name: Run Snapshot
      run: |
        cd ./jobs/snapshot
        node index.js

    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        author_name: Parkour History Bot
        author_email: parkour.history.project@gmail.com
        message: 'Update Snapshot'
        add: './docs/_data/snapshot.json'
        push: true
