on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    container: node:16-bullseye
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup app dependencies
      run: |
        cd ./jobs/snapshot
        npm install

    - name: Run Snapshot
      with:
          PG_CONNECTION_URL: "${{secrets.PG_CONNECTION_URL}}"
      run: npm run start
