on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    container: node:16-bullseye
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup app dependencies
      run: |
        cd ./jobs/snapshot
        npm install

    - name: Run Snapshot
      env:
        PG_CONNECTION_URL: "${{secrets.PG_CONNECTION_URL}}"
      run: npm run start

    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        author_name: Parkour History Bot
        author_email: parkour.history.archiver@gmail.com
        message: 'Update Snapshot'
        add: '../../docs/_data/snapshot.json'
        push: true
